parameters:

  # Configure Cross-Site HTTP requests (CORS).
  # Read https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
  # for more information about the topic in general.
  # Note: By default the configuration is disabled.
  cors.config:
    enabled: true
    # Configure requests allowed from specific origins and sets the
    # Access-Control-Allow-Origin header. For example,
    # ['https://www.drupal.org'] or ['*'] to allow any origin to access your
    # resource. See
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
    allowedOrigins: ['*']
