tool.plugin.tool_belt:user_block:
  type: mapping
  mapping:
    user:
      type: mapping
      label: User
      mapping:
        entity_type_id:
          type: string
          label: 'Entity type'
          constraints:
            NotNull: {  }
        entity_id:
          type: integer
          label: 'Entity ID'
          constraints:
            NotNull: {  }
      constraints:
        NotNull: {  }
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:user_unblock:
  type: mapping
  mapping:
    user:
      type: mapping
      label: User
      mapping:
        entity_type_id:
          type: string
          label: 'Entity type'
          constraints:
            NotNull: {  }
        entity_id:
          type: integer
          label: 'Entity ID'
          constraints:
            NotNull: {  }
      constraints:
        NotNull: {  }
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:user_remove_role:
  type: mapping
  mapping:
    user:
      type: mapping
      label: User
      mapping:
        entity_type_id:
          type: string
          label: 'Entity type'
          constraints:
            NotNull: {  }
        entity_id:
          type: integer
          label: 'Entity ID'
          constraints:
            NotNull: {  }
      constraints:
        NotNull: {  }
    role_id:
      type: string
      label: 'Role ID'
      nullable: true
      constraints:
        PrimitiveType: {  }
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:user_add_role:
  type: mapping
  mapping:
    user:
      type: mapping
      label: User
      mapping:
        entity_type_id:
          type: string
          label: 'Entity type'
          constraints:
            NotNull: {  }
        entity_id:
          type: integer
          label: 'Entity ID'
          constraints:
            NotNull: {  }
      constraints:
        NotNull: {  }
    role_id:
      type: string
      label: 'Role ID'
      nullable: true
      constraints:
        PrimitiveType: {  }
  constraints:
    FullyValidatable: {  }
