tool.plugin.tool_belt:log_message:
  type: mapping
  mapping:
    message:
      type: string
      label: Message
      nullable: true
    level:
      type: string
      label: 'Log Level'
      nullable: true
      constraints:
        Choice:
          choices:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
            - debug
          message: null
    channel:
      type: string
      label: Channel
      nullable: true
    context:
      type: mapping
      label: Context
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:send_email:
  type: mapping
  mapping:
    recipient:
      type: email
      label: Recipient
      nullable: true
    subject:
      type: string
      label: Subject
      nullable: true
    message:
      type: text
      label: Message
      nullable: true
    token_data:
      type: sequence
      label: 'Token Data'
      nullable: true
      sequence:
        type: mapping
        label: 'Token Data'
        nullable: true
        mapping:
          entity_type_id:
            type: string
            label: 'Entity type'
            nullable: true
          entity_id:
            type: integer
            label: 'Entity ID'
            nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:display_message:
  type: mapping
  mapping:
    message:
      type: string
      label: Message
      nullable: true
    type:
      type: string
      label: 'Message Type'
      nullable: true
      constraints:
        Choice:
          choices:
            - status
            - warning
            - error
          message: null
    repeat:
      type: boolean
      label: 'Allow Repeat'
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:system_status:
  type: mapping
  mapping: {  }
  constraints:
    FullyValidatable: {  }
