<?php

/**
 * @file
 * Contains leaflet_chorpleth_custom.module.
 */

use Drupal\views\Plugin\views\ViewsPluginInterface;

/**
 * Implements hook_leaflet_choropleth_color_scale_alter().
 */
function leaflet_chorpleth_custom_leaflet_choropleth_color_scale_alter(array &$color_scale, ViewsPluginInterface &$view_style) {

  if ($view_style->getPluginId() == 'leaflet_choropleth_map' && $view_style->view->current_display === 'page_italian_provinces_choropleth_xx') {
    $language_manager = \Drupal::languageManager();
    $current_language = $language_manager->getCurrentLanguage()->getId();
    $categories = [];
    $vid = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
      'vid' => 'choropleth_categories',
    ]);
    foreach ($vid as $term) {
      if ($term && $term->hasTranslation($current_language)) {
        $translation = $term->getTranslation($current_language);
        $name = $translation->getName();
      }
      else {
        $name = $term->getName();
      }
      $categories[] = $name;
    }

    foreach ($color_scale["legend_items"] as $k => $legend_item) {
      $color_scale["legend_items"][$k]['values']['value'] = $categories[$k] ?? '';
    }
  }

}
