<?php

/**
 * @file
 * Contains leaflet_chorpleth_custom.module.
 */

use Drupal\views\Plugin\views\ViewsPluginInterface;

/**
 * Implements hook_leaflet_choropleth_color_scale_alter().
 */
function leaflet_choropleth_custom_leaflet_choropleth_color_scale_alter(array &$color_scale, ViewsPluginInterface &$view_style) {

  if ($view_style->getPluginId() == 'leaflet_choropleth_map' && $view_style->view->current_display === 'page_italian_provinces_choropleth') {
    // Set custom discrete values (that will replace %value in legend format),
    // from first to last.
    $custom_values = [
      'Much low',
      'Quite low',
      'Welcome',
      'Pretty cool',
      'Very Cool',
      'Ultra Cool',
    ];

    // Replace default legend_items values with $custom_values.
    foreach ($color_scale["legend_items"] as $k => $legend_item) {
      $color_scale["legend_items"][$k]['values']['value'] = $custom_values[$k] ?? '';
    }
  }

}
