tool.plugin.tool_belt:entity_bundle_delete:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
    bundle:
      type: string
      label: Bundle
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:field_storage_delete:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
      constraints:
        PluginExists:
          manager: entity_type.manager
          interface: Drupal\Core\Entity\ContentEntityInterface
    field_name:
      type: string
      label: 'Field Name'
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:field_storage_update:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
      constraints:
        PluginExists:
          manager: entity_type.manager
          interface: Drupal\Core\Entity\ContentEntityInterface
    field_name:
      type: string
      label: 'Field Name'
      nullable: true
    cardinality:
      type: integer
      label: Cardinality
      nullable: true
    translatable:
      type: boolean
      label: Translatable
      nullable: true
    settings:
      type: mapping
      label: 'Storage Settings'
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:field_delete:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
      constraints:
        PluginExists:
          manager: entity_type.manager
          interface: Drupal\Core\Entity\ContentEntityInterface
    bundle:
      type: string
      label: Bundle
      nullable: true
    field_name:
      type: string
      label: 'Field Name'
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:field_storage_add:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
      constraints:
        PluginExists:
          manager: entity_type.manager
          interface: Drupal\Core\Entity\ContentEntityInterface
    field_name:
      type: string
      label: 'Field Name'
      nullable: true
      constraints:
        Regex:
          pattern: '/^field_[a-z0-9_]+$/'
          message: 'Field name must start with "field_" and contain only lowercase letters, numbers, and underscores.'
    field_type:
      type: string
      label: 'Field Type'
      nullable: true
      constraints:
        PluginExists:
          manager: plugin.manager.field.field_type
    cardinality:
      type: integer
      label: Cardinality
      nullable: true
    translatable:
      type: boolean
      label: Translatable
      nullable: true
    settings:
      type: mapping
      label: 'Storage Settings'
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:entity_type_list:
  type: mapping
  mapping: {  }
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:entity_bundle_field_definitions:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
    bundle:
      type: string
      label: Bundle
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:field_add:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
      constraints:
        PluginExists:
          manager: entity_type.manager
          interface: Drupal\Core\Entity\ContentEntityInterface
    bundle:
      type: string
      label: Bundle
      nullable: true
    field_name:
      type: string
      label: 'Field Name'
      nullable: true
    label:
      type: string
      label: 'Field Label'
      nullable: true
    description:
      type: string
      label: 'Field Description'
      nullable: true
    required:
      type: boolean
      label: Required
      nullable: true
    settings:
      type: mapping
      label: 'Field Settings'
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:entity_bundle_update:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
    bundle:
      type: string
      label: 'Bundle ID'
      nullable: true
    label:
      type: string
      label: Label
      nullable: true
    properties:
      type: mapping
      label: Properties
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:field_type_definitions:
  type: mapping
  mapping: {  }
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:field_update:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
      constraints:
        PluginExists:
          manager: entity_type.manager
          interface: Drupal\Core\Entity\ContentEntityInterface
    bundle:
      type: string
      label: Bundle
      nullable: true
    field_name:
      type: string
      label: 'Field Name'
      nullable: true
    label:
      type: string
      label: 'Field Label'
      nullable: true
    description:
      type: string
      label: 'Field Description'
      nullable: true
    required:
      type: boolean
      label: Required
      nullable: true
    settings:
      type: mapping
      label: 'Field Settings'
      nullable: true
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:entity_bundle_definition:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
      constraints:
        PluginExists:
          manager: entity_type.manager
          interface: Drupal\Core\Entity\ContentEntityInterface
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:entity_bundle_list:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
      constraints:
        PluginExists:
          manager: entity_type.manager
          interface: Drupal\Core\Entity\ContentEntityInterface
  constraints:
    FullyValidatable: {  }

tool.plugin.tool_belt:entity_bundle_add:
  type: mapping
  mapping:
    entity_type_id:
      type: string
      label: 'Entity Type ID'
      nullable: true
    bundle:
      type: string
      label: 'Bundle ID'
      nullable: true
    label:
      type: string
      label: Label
      nullable: true
    properties:
      type: mapping
      label: Properties
      nullable: true
  constraints:
    FullyValidatable: {  }
