<?php

/**
 * @file
 * Hook implementations for media_image_exif_importer module.
 */

/**
 * Implements hook_media_source_info_alter().
 */
function media_image_exif_importer_media_source_info_alter(array &$definitions) {
  // Hijack core's Image source plugin and make it use our class instead.
  $definitions['image']['class'] = 'Drupal\media_image_exif_importer\Plugin\media\Source\ImageWithExif';
}
