<?php

/**
 * @file
 * Contains geofield_3111.module.
 */

use Drupal\geofield_map\Plugin\views\style\GeofieldGoogleMapViewStyle;

/**
 * Implements hook_leaflet_map_view_style_alter().
 */
function geofield_311_leaflet_map_view_style_alter(array &$map_settings) {
  $map_settings["map"]['geojson_app_limit'] = \Drupal::service('geofield_311.service')
    ->getGeojsonAppLimit();
}

/**
 * Implements hook_leaflet_default_widget_alter().
 */
function geofield_311_leaflet_default_widget_alter(array &$map_settings) {
  $map_settings['geojson_app_limit'] = \Drupal::service('geofield_311.service')
    ->getGeojsonAppLimit();
}

/**
 * Implements hook_geofield_map_googlemap_view_style_alter().
 */
function geofield_311_geofield_map_googlemap_view_style_alter(array &$map_settings, GeofieldGoogleMapViewStyle &$view_style) {
  $map_settings['geojson_app_limit'] = \Drupal::service('geofield_311.service')
    ->getGeojsonAppLimit();
}

/**
 * Returns leaflet map default settings.
 */
function geofield_311_leaflet_map_default_settings() {
  return [
    'dragging' => TRUE,
    'touchZoom' => TRUE,
    'scrollWheelZoom' => TRUE,
    'doubleClickZoom' => TRUE,
    'zoomControl' => TRUE,
    'attributionControl' => TRUE,
    'trackResize' => TRUE,
    'fadeAnimation' => TRUE,
    'zoomAnimation' => TRUE,
    'closePopupOnClick' => TRUE,
    'minZoom' => 2,
    'maxZoom' => 20,
    'zoom' => 15,
    'layerControl' => TRUE,
    'layerControlOptions' => [
      'position' => 'topright',
      'collapsed' => TRUE,
    ],
  ];
}

/**
 * Implements hook_leaflet_map_info().
 */
function geofield_311_leaflet_map_info() {
  $map_info = [];
  $map_info['multilayers'] = [
    'label' => 'Multilayers',
    'description' => t('Multilayers'),
    'settings' => geofield_311_leaflet_map_default_settings(),
    'layers' => [
      'Openstreetmap' => [
        'urlTemplate' => 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
        'options' => [
          "maxZoom" => 20,
          'attribution' => '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        ],
      ],
      'Stadia Alidade Smooth' => [
        'type' => 'vector',
        'urlTemplate' => '//tiles.stadiamaps.com/styles/alidade_smooth.json',
        'options' => [
          'attribution' => '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a>, &copy; <a href="https://openmaptiles.org/">OpenMapTiles</a> &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
        ],
      ],
/*      'Stadia Alidade Dark' => [
        'type' => 'vector',
        'urlTemplate' => '//tiles.stadiamaps.com/styles/alidade_smooth_dark.json',
        'options' => [
          'attribution' => '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a>, &copy; <a href="https://openmaptiles.org/">OpenMapTiles</a> &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
        ],
      ],*/
      'Taranto-Viva Topomaps' => [
        'type' => 'vector',
        'urlTemplate' => '//api.maptiler.com/maps/019f2315-d543-7f3f-9897-7ea272fb2007/style.json?key=OIQHXCpngQEP6dfvC5nq',
        'options' => [
          // 'attribution' => '&copy; <a href="https://www.maptiler.com/">Map Tiler</a>',
        ],
      ],
      'Google Roads' => [
        'type' => 'google',
        'urlTemplate' => '//mt{s}.googleapis.com/vt?x={x}&y={y}&z={z}',
        'options' => [
          "minZoom" => 0,
          "maxZoom" => 20,
          'attribution' => 'Map data &copy; <a href="http://googlemaps.com">Google</a>',
          'detectRetina' => FALSE,
          'subdomains' => [0, 1, 2, 3],
        ],
      ],
      'Google Hybrid' => [
        'type' => 'google',
        'urlTemplate' => '//mt{s}.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}',
        'options' => [
          "minZoom" => 0,
          "maxZoom" => 20,
          'attribution' => 'Map data &copy; <a href="http://googlemaps.com">Google</a>',
          'detectRetina' => FALSE,
          'subdomains' => ['0', '1', '2', '3'],
        ],
      ],
/*      'Google Terrain' => [
        'type' => 'google',
        'urlTemplate' => '//mt{s}.google.com/vt/lyrs=p&x={x}&y={y}&z={z}',
        'options' => [
          "minZoom" => 0,
          "maxZoom" => 20,
          'attribution' => 'Map data &copy; <a href="http://googlemaps.com">Google</a>',
          'detectRetina' => FALSE,
          'subdomains' => ['0', '1', '2', '3'],
        ],
      ],*/
/*      'Stamen TonerLite' => [
        'type' => 'vector',
        'urlTemplate' => '//tiles.stadiamaps.com/styles/stamen_toner.json',
        'options' => [
          'attribution' => '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a>, &copy; <a href="https://openmaptiles.org/">OpenMapTiles</a> &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
        ],
      ],*/
    ],
  ];

  $map_info['taranto_viva_topomaps'] = [
    'label' => 'Taranto-Viva Topomaps',
    'description' => t('Taranto-Viva Topomaps.'),
    'settings' => geofield_311_leaflet_map_default_settings(),
    'layers' => [
      'Taranto-Viva Topomaps' => [
        'type' => 'vector',
        'urlTemplate' => '//api.maptiler.com/maps/019f2315-d543-7f3f-9897-7ea272fb2007/style.json?key=OIQHXCpngQEP6dfvC5nq',
        'options' => [
         // 'attribution' => '&copy; <a href="https://www.maptiler.com/">Map Tiler</a>, &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
        ],
      ],
    ],
  ];

  $map_info['google_roads'] = [
    'label' => 'Google Roads',
    'description' => t('Leaflet default map.'),
    'settings' => [
      'dragging' => TRUE,
      'touchZoom' => TRUE,
      'scrollWheelZoom' => TRUE,
      'doubleClickZoom' => TRUE,
      'zoomControl' => TRUE,
      'attributionControl' => TRUE,
      'trackResize' => TRUE,
      'fadeAnimation' => TRUE,
      'zoomAnimation' => TRUE,
      'closePopupOnClick' => TRUE,
    ],
    'layers' => [
      'Google Roads' => [
        'type' => 'google',
        'urlTemplate' => '//mt{s}.googleapis.com/vt?x={x}&y={y}&z={z}',
        'options' => [
          "minZoom" => 0,
          "maxZoom" => 20,
          'attribution' => 'Map data &copy; <a href="http://googlemaps.com">Google</a>',
          'detectRetina' => FALSE,
          'subdomains' => [0, 1, 2, 3],
        ],
      ],
    ],
  ];

  return $map_info;
}

/**
 * Implements hook_library_info_alter().
 *
 *  Make the geofield_311 library loading before leaflet js library.
 */
function geofield_311_library_info_alter(&$libraries, $extension) {
  if ($extension == "leaflet") {
    // $libraries['leaflet']['dependencies'][] = 'geofield_311/geofield_311';
  }
}
