<?php

/**
 * @file
 * Updates to the watchdog statistics view.
 */

use Symfony\Component\Yaml\Yaml;

/**
 * Updates the watchdog statistics view.
 */
function watchdog_statistics_update_view() {
  $config_name = 'views.view.watchdog_statistics';
  $config_module_path = \Drupal::service('extension.path.resolver')->getPath('module', 'watchdog_statistics') . '/config/install/' . $config_name . '.yml';

  $config_module = Yaml::parse(file_get_contents($config_module_path));
  $config_installed = \Drupal::configFactory()->getEditable($config_name);
  $uuid = $config_installed->get('uuid');
  $config_installed->setData($config_module)->save();
  // Ensure uuid is not lost.
  $config_installed->set('uuid', $uuid);
  $config_installed->save();
}

/**
 * Allows exclude specific message types.
 */
function watchdog_statistics_update_10003() {
  watchdog_statistics_update_view();
}

/**
 * Adds the date filters.
 */
function watchdog_statistics_update_10002() {
  watchdog_statistics_update_view();
}

/**
 * Adds the date filters.
 */
function watchdog_statistics_update_10001() {
  watchdog_statistics_update_view();
}
