<?php

/**
 * @file
 * Contains italo_module.module.
 */

use Drupal\node\NodeInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_popup_message_parameters_alter().
 *
 * Attach to the popup_message the Node target set in the
 * geocms.settings.geocms_info_popup_settings.contents
 * rendered in "popup" display node.
 *
 * @note: this $popup_message_parameters["body"] is only working until
 * drupal/popup_message: 3.0.3 version.
 */
function geocms_popup_message_parameters_alter(&$popup_message_parameters) {
  $config = Drupal::config('geocms.settings');
  $geocms_info_popup_contents = [];
  if (!empty($config->get('geocms_info_popup_settings.contents'))) {
    foreach ($config->get('geocms_info_popup_settings.contents') as $id) {
      $geocms_info_popup_contents[] = Node::load($id['target_id']);
    }
  }

  if (!empty($geocms_info_popup_contents)) {
    $view_mode = 'popup';
    foreach ($geocms_info_popup_contents as $popup_content) {
      if ($popup_content instanceof NodeInterface) {
        $build = \Drupal::entityTypeManager()->getViewBuilder('node')->view($popup_content, $view_mode);
        $output = \Drupal::service('renderer')->renderInIsolation($build);
        $popup_message_parameters["body"] = $popup_message_parameters["body"] . $output;
      }

    }
  }
}
