<?php

/**
 * @file
 * Contains hook implementations for media_image_metadata.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Plugin\Field\FieldType\FileFieldItemList;
use Drupal\image\Plugin\Field\FieldWidget\ImageWidget;
use Drupal\media\Entity\MediaType;
use Drupal\media\MediaInterface;
use Drupal\media_image_metadata\Form\ImageWithMetadataUploadForm;
use Drupal\media_image_metadata\Plugin\media\Source\ImageWithMetadata;

/**
 * Implements hook_media_source_info_alter().
 */
function media_image_metadata_media_source_info_alter(array &$definitions) {
  // Make the Image source plugin use our source class instead.
  $definitions['image']['class'] = ImageWithMetadata::class;
  // If Media Library is installed, use our version of the form as well.
  if (\Drupal::moduleHandler()->moduleExists('media_library')) {
    $definitions['image']['forms']['media_library_add'] = ImageWithMetadataUploadForm::class;
  }
}

/**
 * Implements hook_field_widget_complete_form_alter().
 */
function media_image_metadata_field_widget_complete_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  if (($context['widget'] ?? NULL instanceof ImageWidget) &&
    ($context['items'] instanceof FileFieldItemList)) {
    $definition = $context['items']->getFieldDefinition();
    if ($definition->getTargetEntityTypeId() === 'media') {
      $bundle = $definition->getTargetBundle();
      // Get the media source plugin config for this media bundle.
      $media_type = MediaType::load($bundle);
      $source = $media_type->getSource();
      $source_config = $source->getConfiguration();
      // Only extract and populate alt if configured to do so.
      if (!empty($source_config['populate_alt_property'])) {
        $field_widget_complete_form['widget'][0]['#process'][] = 'media_image_metadata_image_widget_alt_process';
      }
    }
  }
}

/**
 * Process callback for the image widget.
 */
function media_image_metadata_image_widget_alt_process($element, FormStateInterface $form_state, $form) {
  // Nothing to do if the 'alt' property already contains a value.
  if (!empty($element['alt']['#default_value'])) {
    return $element;
  }
  $stored_media = $form_state->get('media');
  if (empty($stored_media[0])) {
    // Try to get it from where Entity Browser stores it.
    $stored_media = $form_state->get('uploaded_entities');
  }
  if (!is_array($stored_media) || empty($stored_media[0])) {
    return $element;
  }
  // We need to figure out which of the uploaded media items is the one we are
  // interested in.
  $element_fid = $element['fids']['#value'][0] ?? 0;
  foreach ($stored_media as $candidate_media) {
    assert($candidate_media instanceof MediaInterface);
    $candidate_fid = $candidate_media->getSource()->getSourceFieldValue($candidate_media);
    if ($element_fid == $candidate_fid) {
      $media = $candidate_media;
      break;
    }
  }
  if (!($media instanceof MediaInterface)) {
    return $element;
  }
  // Get the 'alt' metadata from the media entity.
  $alt = $media->getSource()->getMetadata($media, 'alt');
  if (!empty($alt)) {
    $element['alt']['#default_value'] = $alt;
  }
  return $element;
}
