<?php

/**
 * @file
 * Install, update, and uninstall functions for the LiteLLM module.
 */

/**
 * Notify that OpenAI provider is not a requirement anymore.
 */
function ai_provider_litellm_update_10001() {
  // This is informational only - we still need to have the OpenAI provider.
  return t('The LiteLLM provider no longer requires the OpenAI provider module. If you are not using it, you can uninstall it.');
}
