views.filter.target_entity_type_filter:
  type: views.filter.in_operator
  label: 'Target entity type filter'

views.filter.source_entity_type_filter:
  type: views.filter.in_operator
  label: 'Source entity type filter'

views.filter.category_filter:
  type: views.filter.in_operator
  label: 'Category filter'

views.filter.subcategory_filter:
  type: views.filter.in_operator
  label: 'Subcategory filter'

views.filter.source_bundle_filter:
  type: views.filter.in_operator
  label: 'Source bundle filter'

views.filter.source_langcode_filter:
  type: views.filter.in_operator
  label: 'Source langcode filter'

views.filter.target_bundle_filter:
  type: views.filter.in_operator
  label: 'Target bundle filter'

views.filter.target_langcode_filter:
  type: views.filter.in_operator
  label: 'Target langcode filter'

views.filter.target_schema_filter:
  type: views.filter.in_operator
  label: 'Target schema filter'
  mapping:
    value:
      type: sequence
      label: 'Values'
      sequence:
        type: string
        label: 'Value'

views.filter.target_type_link_filter:
  type: views.filter.in_operator
  label: 'Target type link filter'

views.filter.target_scheme_filter:
  type: views.filter.in_operator
  label: 'Target type link filter'
